version: "3.8"
services:
  r1:
    image: frrouting/frr:latest
    container_name: ospf_r1
    cap_add: [NET_ADMIN, SYS_ADMIN]
    networks:
      ospf_net:
        ipv4_address: 10.0.0.1
    volumes:
      - ./frr/r1/daemons:/etc/frr/daemons
      - ./frr/r1/frr.conf:/etc/frr/frr.conf

  r2:
    image: frrouting/frr:latest
    container_name: ospf_r2
    cap_add: [NET_ADMIN, SYS_ADMIN]
    networks:
      ospf_net:
        ipv4_address: 10.0.0.2
    volumes:
      - ./frr/r2/daemons:/etc/frr/daemons
      - ./frr/r2/frr.conf:/etc/frr/frr.conf

networks:
  ospf_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
